### ISSUE TITLE
对新版的xxl-job，注册不上去，报错

### ISSUE THREAD

**Issue by fantlz** [xuanye/DotXxlJob#2]
fail: DotXxlJob.Core.AdminClient[0]
      request admin error.Response status code does not indicate success: 404 ().
System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 ().
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at DotXxlJob.Core.AdminClient.DoPost(HttpClient client, AddressEntry address, Byte[] postBuf) in D:\work\code\cshrap\github\DotXxlJob-master\src\DotXxlJob.Core\AdminClient.cs:line 172
   at DotXxlJob.Core.AdminClient.InvokeRpcService(String methodName, List`1 parameterTypes, Object parameters, Boolean polling) in D:\work\code\cshrap\github\DotXxlJob-master\src\DotXxlJob.Core\AdminClient.cs:line 107

**Comment by fantlz** [comment]
2.2.0版本

**Comment by xuanye** [comment]
404 是不是地址不对，2.2我看了下默认的管理地址不是根目录
```  
### web
server.port=8080
server.servlet.context-path=/xxl-job-admin
```
那你对应执行器的管理地址也要配置修改下

**Comment by fantlz** [comment]
谢谢呀，后面看代码发现了，要加 /xxl-job-admin ，但是执行器还是注册不上的，因为匹配不到注册的接口
![image](https://user-images.githubusercontent.com/41730691/81381538-7b8c9780-913f-11ea-9170-3a535a209611.png)

**Comment by xuanye** [comment]
2.2修改为restful 接口了。。这个有点搞，至少应该要提供兼容的方案，
晚点我升级下

**Comment by xuanye** [comment]
最新的v2.0版本已经支持xxl-jobv2.2版本的restful接口
