### ISSUE TITLE
执行管理器可以注册上去，执行任务xxljob-admin出现500 Connection refused

### ISSUE THREAD

**Issue by zhangjmhappy** [xuanye/DotXxlJob#5]
java xxl-job-admin 错误信息
```
c.x.job.core.util.XxlJobRemotingUtil - Connection refused: connect
java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at sun.net.www.http.HttpClient.New(HttpClient.java:339)
	at sun.net.www.http.HttpClient.New(HttpClient.java:357)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984)
	at com.xxl.job.core.util.XxlJobRemotingUtil.postBody(XxlJobRemotingUtil.java:95)
	at com.xxl.job.core.biz.client.ExecutorBizClient.run(ExecutorBizClient.java:43)
	at com.xxl.job.admin.core.trigger.XxlJobTrigger.runExecutor(XxlJobTrigger.java:211)
	at com.xxl.job.admin.core.trigger.XxlJobTrigger.processTrigger(XxlJobTrigger.java:164)
	at com.xxl.job.admin.core.trigger.XxlJobTrigger.trigger(XxlJobTrigger.java:89)
	at com.xxl.job.admin.core.thread.JobTriggerPoolHelper$3.run(JobTriggerPoolHelper.java:95)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
10:29:54.179 logback [xxl-job, admin JobTriggerPoolHelper-fastTriggerPool-329495173] ERROR c.x.job.core.util.XxlJobRemotingUtil - Connection refused: connect
```

执行日志
```
任务触发类型：手动触发
调度机器：192.168.0.221
执行器-注册方式：自动注册
执行器-地址列表：[http://192.168.0.221:5000/]
路由策略：第一个
阻塞处理策略：单机串行
任务超时时间：0
失败重试次数：0

>>>>>>>>>>>触发调度<<<<<<<<<<<
触发调度：
address：http://192.168.0.221:5000/
code：500
msg：xxl-rpc remoting error(Connection refused: connect), for url : http://192.168.0.221:5000/run
```
是.netcore端配置有什么问题么？

**Comment by xuanye** [comment]
看下你的地址和端口  都是对的嘛？

**Comment by zhangjmhappy** [comment]
5000端口么？注册上去的端口和appsettings.json文件port属性是一样的都是5000 ，192.168.0.221这个是我本机ip，用官方给java版本的xxl-job-springboot的demo可以执行成功。

appsettings.json文件如下
```
{
  "Logging": {
    "LogLevel": {
      "Default": "Information"
    }
  },
  "xxlJob": {
    "adminAddresses": "http://192.168.0.221:8080/xxl-job-admin",
    "appName": "xxl-job-executor-sample",
    "specialBindAddress": "192.168.0.221",
    "port": 5000,
    "autoRegistry": true,
    "accessToken": "",
    "logRetentionDays": 30
  }
 
}
```
xxl-job-admin

![image](http://ww1.sinaimg.cn/large/aee9d9f0gy1gglwspdhwrj21640583yt.jpg)

**Comment by zhangjmhappy** [comment]
用telnet 192.168.0.221 5000 连接不上，是不是.net core执行器客户端的内嵌服务器没有开启？xxl-job调度中心去连接注册上来的地址连接不上。xxl-job的版本是2.2，dotnet core sdk版本2.2.207

**Comment by zhangjmhappy** [comment]
执行dotnet add package DotXxlJob.Core命令出现 “error: Value cannot be null. (Parameter 'path1')”错误。
```
C:\dotnet_workspace\DotXxlJob-master\src\DotXxlJob.Core>dotnet add package DotXxlJob.Core
  正在确定要还原的项目…
  Writing C:\Users\ygc\AppData\Local\Temp\tmp4280.tmp
info : 正在将包“DotXxlJob.Core”的 PackageReference 添加到项目“C:\dotnet_workspace\DotXxlJob-master\src\DotXxlJob.Core\DotXxlJob.Core.csproj”。
info : 正在还原 C:\dotnet_workspace\DotXxlJob-master\src\DotXxlJob.Core\DotXxlJob.Core.csproj 的包...
error: 检测到循环。
error:   DotXxlJob.Core -> DotXxlJob.Core (>= 0.0.0).
info : 包“DotXxlJob.Core”与项目“C:\dotnet_workspace\DotXxlJob-master\src\DotXxlJob.Core\DotXxlJob.Core.csproj”中指定的所有框架均兼容。
error: Value cannot be null. (Parameter 'path1')
```

**Comment by xuanye** [comment]
首先你要确保 你的。netcore 网站绑定在了192.168.0.221 5000 端口上啊，你看下源码中的示例 是localhost的，
具体的端口 ，你应该用dotnet run 看看到底绑定了哪个端口，应该有console log的

**Comment by zhangjmhappy** [comment]
谢谢，可以了弄成127.0.0.1就行了
